#!/usr/bin/env bash
#
# Docker HTTP proxy wrapper script
#
# Copyright (c) 2016 Tomas Gerulaitis <t.gerulaitis@gmail.com>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

script=${0##*/}
command=$1

name="http-proxy"
certs_dir=$HOME/.docker/ssl
status=$(docker inspect --format "{{ .State.Running }}" $name 2> /dev/null)

usage="\
Usage:
    $script <command>

Available commands:
    name     Print out the name of the HTTP proxy container.
    status   Print out the status of the HTTP proxy container.
    start    Start the HTTP proxy container, creating it if necessary.
    stop     Stop the HTTP proxy container.
    rm       Destroy a stopped HTTP proxy container, including its volumes.

Description:
    $script is a wrapper to easily manage the meanbee/nginx-proxy docker
    container. The container itself (extended from jwilder/nginx-proxy)
    accepts incomming HTTP and HTTPS requests and passes them to the
    appropriate docker container based on the request Host header.

    For HTTPS requests, the container uses an appropriate SSL certificate
    mounted from $certs_dir.

    For more information on the docker HTTP proxy container, see
    https://github.com/meanbee/docker-nginx-proxy and https://github.com/jwilder/nginx-proxy

Author:
    Tomas Gerulaitis
    http://tgerulaitis.com/
    t.gerulaitis@gmail.com
"

case "$command" in
start)
    case "$status" in
        true)
            echo "Proxy container is already running!"
            exit 1
            ;;
        false)
            docker start $name
            ;;
        *)
            docker run -d \
                -p 80:80 \
                -p 443:443 \
                -v $certs_dir:/etc/nginx/certs \
                -v /var/run/docker.sock:/tmp/docker.sock \
                --name $name \
                meanbee/nginx-proxy
            ;;
    esac
    ;;
stop)
    if [ "$status" == "true" ]; then
        docker stop $name
    else
        echo "Proxy container is not running!"
        exit 1
    fi
    ;;
rm)
    if [ -n "$status" ]; then
        docker rm -v $name
    else
        echo "Nothing to remove!"
        exit 1
    fi
    ;;
name)
    echo $name
    ;;
status)
    case "$status" in
        true)
            echo "Proxy container is running"
            ;;
        false)
            echo "Proxy container is stopped"
            ;;
        *)
            echo "Proxy container has not been setup"
            ;;
    esac
    ;;
*)
    echo -e "$usage"
    exit 1
    ;;
esac

exit 0
